title:             igloo090
email:             csj8791@naver.com
description:       welcome :)
author:            igloo090
baseurl:           ""
url:               "https://igloo090.github.io/"

# Social Profiles
#twitter_username:  testtw
#github_username:   testgit
#facebook_username: testfb

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
#https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll
