title:             Welcome to my blog
email:             x@x.com
description:       welcome :)
author:            welcome
baseurl:           ""
url:               "https://igloo090.github.io/"

# Social Profiles
twitter_username:  testtw
github_username:   testgit
facebook_username: testfb

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
